title: Morakinyo Oluwabukunmi
description: > 
   
  I am a Data Analyst. My main area of interest is transforming raw data into insightful 
  information and give knowlegdeable recommendations. I have honed my experience in performing ETL, data cleansing,
  data analysis, and visualization. I am proficient in Microsoft Excel, Tableau, MySQL, Python and in using these tools to 
  provide solutions to complex data problems. I am ready to use my analytical skills to solve challenges as an 
  individual and part of a team.
baseurl: "/example"
github: "http://www.github.com/bhikey1"
linkedIn: "http://www.linkedin.com/in/morakinyo-oluwabukunmi"

theme: jekyll-theme-minimal
